version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://app_user:app_password@mongo:27017/auth_db?authSource=auth_db
      - JWT_SECRET=prefiroQueijadasDeSintra
    depends_on:
      - mongo
    networks:
      - dsa-network      
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password_ppi
      - MONGO_INITDB_DATABASE=auth_db
    networks:
      - dsa-network
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

networks:
  dsa-network:
    driver: bridge

volumes:
  mongodb_data:
