services:
  backend:
    build: ./backend
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/auth_db
      - JWT_SECRET=seuSegredoSuperSecreto
    depends_on:
      - mongo
    networks:
      - dsa-network      
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senhaadmin
      - MONGO_INITDB_DATABASE=auth_db
      - MONGO_INITDB_USERNAME=app_user
      - MONGO_INITDB_PASSWORD=app_password
    networks:
      - dsa-network
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  dsa-network:
    driver: bridge

volumes:
  mongodb_data: